# Generated by Django 3.2.6 on 2021-09-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('avatar_xl', models.ImageField(height_field='500', null=True, upload_to='media/avatars/xl', width_field='400')),
                ('avatar_lg', models.ImageField(height_field='100', null=True, upload_to='media/avatars/lg', width_field='100')),
                ('avatar_sm', models.ImageField(height_field='32', null=True, upload_to='media/avatars/sm', width_field='32')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=12, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('count_success_tours', models.IntegerField()),
                ('social_networks', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Blogger',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('points', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Tour',
            },
        ),
        migrations.CreateModel(
            name='BloggerTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(null=True)),
                ('date_invited', models.DateField(null=True)),
                ('invitation_status', models.CharField(choices=[('i', 'invited'), ('a', 'accepted'), ('r', 'regected')], default='i', max_length=1)),
                ('was_skipped', models.BooleanField()),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogger')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tour')),
            ],
        ),
        migrations.AddField(
            model_name='blogger',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloggers', to='api.job'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='tours',
            field=models.ManyToManyField(related_name='bloggers', through='api.BloggerTour', to='api.Tour'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogger_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
